name: Publish BDD results to Cucumber Studio

on:
#  pull_request:
#  push:
#    branches:
#      - "main"

jobs:
  test:
    name: run godog and publish results to cucumber studio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install Godog
        run: go get github.com/cucumber/godog/cmd/godog@v0.11.0


      - name: Execute Cucumber BDD Specifications
        run: godog --format cucumber:test-results/cucumber-report.json




# commit the changed test-results report
# see https://github.com/stefanzweifel/git-auto-commit-action for details
#      - uses: stefanzweifel/git-auto-commit-action@v4

#        with:
#          # which file(s) to add
#          file_pattern: test-results/cucumber-report.*

#          commit_message: "new cucumber bdd test-results report, created by github action run"

          # Optional. Disable dirty check and always try to create a commit and push
#          skip_dirty_check: true

          # Optional. Skip internal call to `git fetch`
#          skip_fetch: true
